#!/usr/bin/env python

import json
import yaml

yaml_file = "shapes.yml"
json_file = "shapes.jsonld"

with open(yaml_file) as f:
    y = yaml.safe_load(f)

with open(json_file, "w") as g:
    j = json.dumps(y, indent=2)
    print(j)
    g.write(j)
