#!/usr/bin/env python

import json
import yaml
import sys

yaml_file = sys.argv[1]
json_file = "./schema.jsonld"

with open(yaml_file) as f:
    y = yaml.safe_load(f)

j = json.dumps(y, indent=2)
print(j)
#with open(json_file, "w") as g:
#    g.write(j)
