{% macro curietouri(curie) -%}
    {%- set prefix, name = curie.split(":") -%}
    {{ prefixes[prefix] ~ name }}
{%- endmacro %}

{% macro link_curie(curie) -%}
    {%- set uri = curietouri(curie) -%}
    {{ uri ~ "[`" ~ curie ~ "`]" }}
{%- endmacro %}

{% macro cardinalities(slot) -%}
    {%- if slot.required and not slot.multivalued -%}
    (1)
    {%- elif slot.required and slot.multivalued -%}
    (1..*)
    {%- elif not slot.required and slot.multivalued -%}
    (0..*)
    {%- elif not slot.required and not slot.multivalued -%}
    (0..1)
    {%- endif -%}
{%- endmacro %}

= {% if title %}{{ title }}{% else %}{{ name }}{% endif %}
:sectnums:

{% if description -%}
{{ description }}
{%- endif %}

'''

[#metadata]
--
URI:: {{ id }}[{{ id }}]
Version:: {{version}}
Version of:: {{ instantiates }}[{{ instantiates }}]
Conforms to:: {{ conforms_to }}
Artifacts:: link:./prof_ap_cim.shacl.ttl[SHACL (Turtle),window=read-later] | link:./prof_ap_cim.linkml.yml[LinkML (YAML),window=read-later] | link:./prof_ap_cim.context.jsonld[JSON-LD context (JSON-LD),window=read-later]
--

{#[nonum]
== Abstract
#TODO#.#}

== Introduction

This is an application profile of PROF for defining CIM profiles.

== Status
#TODO#.

== License
#TODO#.

== Conformance
#TODO#.

== Terminology
#TODO#.

== Schema

.Schema
[d2]
----
direction: down
{% for class_name, class_ in classes.items() %}
{{class_name}}: "{{ class_name }} <<{{ class_.class_uri }}>>" {
  shape: sql_table
  {% for attr_name, attr in class_.attributes.items() -%}
  {%- if attr.range not in classes -%}
  "{{ attr_name }}": {{ attr.slot_uri}} {constraint: {{ attr.range }} {{ cardinalities(attr) }}}
  {% endif -%}
  {% endfor %}
}
{% for attr_name, attr in class_.attributes.items() -%}
{%- if attr.range in classes -%}
"{{ class_name }}" -> "{{ attr.range }}": {{ attr_name }}
{% endif -%}
{% endfor %}
{% endfor %}
----


{% for class_name, class_ in classes.items() -%}
=== Class: {{ class_name }}
[horizontal]
URI:: {{ link_curie(class_.class_uri) }}

{% if class_.description %}{{ class_.description }}{% endif %}

{% for attr_name, attr_ in class_.attributes.items() -%}
{% if loop.first %}
.Profile properties
[cols="1,1,3"]
|===
| Property | Type | Description

{% endif %}
| {{ curietouri(attr_.slot_uri) }}[`{{ attr_name }}`, title={{attr_.slot_uri}}]
a|
[unstyled]
* `{{ attr_.range }}`
* {{ cardinalities(attr_) }}
| {{ attr_.description }}
{% if loop.last %}
|===
{% endif %}
{% endfor %}

{% endfor %}


[nonum]
== Appendix A: Diagram Layout profile example

Any RDF serialization will do for profile instances, but it is recommended to make us of the link:./prof_ap_cim.context.jsonld[JSON-LD context,window=read-later]
and write using YAML.

[source,yaml]
----
include::example$diagram_layout_ap.yml[]
----

Note how the user does not need to write any URIs or CURIEs by hand. Moreover, all the `@` characters which indicate special JSON-LD syntax have been aliased
such that the user won't be confused by them.

This YAML can trivially be converted to JSON, rendering a valid JSON-LD serialization of the profile instance:

[source,json]
----
include::example$diagram_layout_ap.jsonld[]
----

[nonum]
== Appendix B: Validating profiles

